**Products**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from pathlib import Path

In [2]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Products.csv"
df = pd.read_csv(file_path)
df

,Product_ID,Product_Name,Category,Sub_Category,Unit_Cost,Selling_Price,Supplier_ID
0,P1000,Product 1,Office,Stationery,344.99,701.83,S131
1,P1001,Product 2,Beauty,Makeup,266.87,460.73,S108
2,P1002,Product 3,Toys,Plush,194.66,268.68,S139
3,P1003,Product 4,Fashion,Footwear,149.63,177.36,S119
4,P1004,Product 5,Office,Office supplies,210.06,288.91,S189
...,...,...,...,...,...,...,...
995,P1995,Product 996,Fmcg,Personal care,106.67,197.06,S110
996,P1996,Product 997,Fmcg,Personal care,130.52,177.40,S125
997,P1997,Product 998,Toys,Action toys,111.23,133.17,S141
998,P1998,Product 999,Home & kitchen,Appliances,188.99,242.41,S126
999,P1999,Product 1000,Automotive,Cleaning,142.69,302.09,S110

In [3]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     1000 non-null   object
 1   Product_Name   1000 non-null   object
 2   Category       1000 non-null   object
 3   Sub_Category   1000 non-null   object
 4   Unit_Cost      1000 non-null   float64
 5   Selling_Price  1000 non-null   float64
 6   Supplier_ID    1000 non-null   object
dtypes: float64(2), object(5)
memory usage: 54.8+ KB

In [4]:
df["Profit"] = (df["Selling_Price"] - df["Unit_Cost"]).round(2)
df["Margin_Pct"] = ((df["Profit"] / df["Selling_Price"])*100).round(2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     1000 non-null   object
 1   Product_Name   1000 non-null   object
 2   Category       1000 non-null   object
 3   Sub_Category   1000 non-null   object
 4   Unit_Cost      1000 non-null   float64
 5   Selling_Price  1000 non-null   float64
 6   Supplier_ID    1000 non-null   object
 7   Profit         1000 non-null   float64
 8   Margin_Pct     1000 non-null   float64
dtypes: float64(4), object(5)
memory usage: 70.4+ KB

In [6]:
# Products with High Profit
df.sort_values(by="Profit", ascending=False).head(10)

,Product_ID,Product_Name,Category,Sub_Category,Unit_Cost,Selling_Price,Supplier_ID,Profit,Margin_Pct
35,P1035,Product 36,Fashion,Women,1581.03,3305.16,S189,1724.13,52.16
325,P1325,Product 326,Fmcg,Personal care,1141.90,2429.46,S152,1287.56,53.00
938,P1938,Product 939,Electronics,Audio,1769.15,2843.31,S152,1074.16,37.78
234,P1234,Product 235,Fashion,Kids,1020.08,2088.04,S187,1067.96,51.15
105,P1105,Product 106,Fashion,Footwear,911.83,1797.32,S171,885.49,49.27
739,P1739,Product 740,Toys,Plush,783.60,1665.74,S111,882.14,52.96
865,P1865,Product 866,Sports,Outdoor,1573.42,2435.79,S177,862.37,35.40
49,P1049,Product 50,Toys,Educational,1425.60,2271.70,S152,846.10,37.25
172,P1172,Product 173,Fashion,Kids,1634.97,2421.23,S116,786.26,32.47
877,P1877,Product 878,Fashion,Men,753.69,1525.83,S131,772.14,50.60

In [7]:
# Products with High Margin%
df.sort_values(by="Margin_Pct", ascending=False).head(10)

,Product_ID,Product_Name,Category,Sub_Category,Unit_Cost,Selling_Price,Supplier_ID,Profit,Margin_Pct
333,P1333,Product 334,Office,Office supplies,16.91,176.31,S158,159.4,90.41
176,P1176,Product 177,Electronics,Accessories,33.40,192.80,S184,159.4,82.68
276,P1276,Product 277,Electronics,Laptops,46.26,205.66,S186,159.4,77.51
82,P1082,Product 83,Toys,Plush,67.73,227.13,S183,159.4,70.18
346,P1346,Product 347,Grocery,Beverages,71.39,230.79,S162,159.4,69.07
658,P1658,Product 659,Electronics,Laptops,76.70,236.10,S117,159.4,67.51
223,P1223,Product 224,Home & kitchen,Appliances,86.42,245.82,S155,159.4,64.84
892,P1892,Product 893,Electronics,Mobiles,99.14,258.54,S130,159.4,61.65
196,P1196,Product 197,Fashion,Women,101.47,260.87,S182,159.4,61.10
580,P1580,Product 581,Automotive,Tools,109.68,269.08,S181,159.4,59.24

In [8]:
result = df.groupby("Category").agg(
    Total_Products = ("Product_ID", "count"),
    Mean_Profit = ("Profit", "mean"),
    Mean_Margin_Pct = ("Margin_Pct", "mean")
).round(2).reset_index().sort_values(by="Mean_Profit", ascending=False)
result

         Category  Total_Products  Mean_Profit  Mean_Margin_Pct
3         Fashion             107       207.17            40.81
8          Sports              96       173.59            38.44
9            Toys             100       169.00            40.31
4            Fmcg             107       167.20            39.49
0      Automotive              91       167.13            39.16
5         Grocery             110       166.76            39.53
2     Electronics             118       166.75            39.67
7          Office              95       153.12            39.61
6  Home & kitchen              82       150.17            38.26
1          Beauty              94       129.01            37.38

In [9]:
df.to_csv("../../Data/Processed/Products.csv", index=False)